import { z } from "zod";

const postCategories = [
  "Agents",
  "Local AI",
  "RAG",
  "DevTools",
  "Product",
  "Evaluation",
  "Ops",
  "Search",
  "Security",
  "Design",
] as const;

const generatedPostDraftSchema = z.object({
  title: z.string().describe("A short, specific post title written in Polish."),
  excerpt: z
    .string()
    .describe("A one-sentence post summary written in Polish."),
  content: z
    .string()
    .describe(
      "The full post body written in Polish. Use 4-6 paragraphs separated by blank lines.",
    ),
  category: z.enum(postCategories),
  readTime: z
    .number()
    .int()
    .positive()
    .describe("Estimated reading time in minutes, for example: 5."),
  imageAlt: z.string().describe("Image alt text written in Polish."),
  imageSearchQuery: z
    .string()
    .describe("A short English search query for choosing an Unsplash image."),
});

const generatedPostJsonSchema = z.toJSONSchema(generatedPostDraftSchema);

export type GeneratedPostDraft = z.infer<typeof generatedPostDraftSchema>;

export async function generatePostDraft(): Promise<GeneratedPostDraft> {
  const apiUrl = process.env.GENAI_API_URL;
  const apiKey = process.env.GENAI_API_KEY;
  const model = process.env.GENAI_MODEL;

  if (!apiUrl) {
    throw new Error("Missing GENAI_API_URL environment variable.");
  }

  if (!apiKey) {
    throw new Error("Missing GENAI_API_KEY environment variable.");
  }

  if (!model) {
    throw new Error("Missing GENAI_MODEL environment variable.");
  }

  const response = await fetch(apiUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        {
          role: "system",
          content:
            "You are an editor for a technical AI blog. Write all user-facing post fields in natural Polish with Polish diacritics. Be concrete, calm, and practical. Avoid marketing language.",
        },
        {
          role: "user",
          content: [
            "Generate one fresh post for the AI Daily Notes feed.",
            "The topic should cover practical AI usage in products, automation, developer workflows, evaluation, search, security, costs, or design.",
            "Do not mention that the post was generated by AI.",
            "Return only a valid JSON object matching this JSON Schema:",
            JSON.stringify(generatedPostJsonSchema),
          ].join("\n\n"),
        },
      ],
      temperature: 0.85,
      response_format: {
        type: "json_object",
      },
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`GenAI request failed with ${response.status}: ${details}`);
  }

  const data = (await response.json()) as {
    choices?: Array<{
      message?: {
        content?: string;
      };
    }>;
  };
  const outputText = data.choices?.[0]?.message?.content;

  if (!outputText) {
    throw new Error("GenAI response did not include message content.");
  }

  return parseGeneratedPostDraft(outputText);
}

function parseGeneratedPostDraft(value: string): GeneratedPostDraft {
  try {
    return generatedPostDraftSchema.parse(JSON.parse(value));
  } catch (error) {
    const details =
      error instanceof Error ? error.message : "Unknown parse error.";

    throw new Error(`Failed to parse generated post draft: ${details}`);
  }
}
