import { z } from "zod";

import type { RecentPostContext, ResearchSource } from "@/lib/research";

const postCategories = [
  "Nowinki",
  "Products",
  "Robotics",
  "Gadgets",
  "Science",
  "Zdrowie",
  "Dom",
  "Praca",
  "Kultura",
  "Transport",
  "Edukacja",
] as const;

const generatedPostSourceSchema = z.object({
  title: z.string(),
  publisher: z.string(),
  url: z.url(),
});

const generatedPostDraftSchema = z.object({
  title: z.string().describe("A short, specific post title written in Polish."),
  excerpt: z
    .string()
    .describe("A one-sentence, non-technical post summary written in Polish."),
  content: z
    .string()
    .min(800)
    .describe(
      "The full post body written in Polish for non-technical readers. It must have at least 800 characters. Use 4-6 short paragraphs separated by blank lines.",
    ),
  category: z.enum(postCategories),
  readTime: z
    .number()
    .int()
    .positive()
    .describe("Estimated reading time in minutes, for example: 5."),
  imageAlt: z.string().describe("Image alt text written in Polish."),
  imageSearchQuery: z
    .string()
    .describe("A short English search query for choosing an Unsplash image."),
  sources: z
    .array(generatedPostSourceSchema)
    .min(1)
    .max(4)
    .describe(
      "Sources selected only from the provided source library. Do not invent URLs.",
    ),
});

const generatedPostJsonSchema = z.toJSONSchema(generatedPostDraftSchema);

export type GeneratedPostDraft = z.infer<typeof generatedPostDraftSchema>;

export async function generatePostDraft(
  researchSources: ResearchSource[],
  recentPosts: RecentPostContext[] = [],
): Promise<GeneratedPostDraft> {
  const apiUrl = process.env.GENAI_API_URL;
  const apiKey = process.env.GENAI_API_KEY;
  const model = process.env.GENAI_MODEL;

  if (!apiUrl) {
    throw new Error("Missing GENAI_API_URL environment variable.");
  }

  if (!apiKey) {
    throw new Error("Missing GENAI_API_KEY environment variable.");
  }

  if (!model) {
    throw new Error("Missing GENAI_MODEL environment variable.");
  }

  if (researchSources.length < 2) {
    throw new Error("Not enough research sources to generate a grounded post.");
  }

  const response = await fetch(apiUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        {
          role: "system",
          content:
            "You are an editor for an accessible AI news blog for non-technical readers. Write all user-facing post fields in natural Polish with Polish diacritics. Be curious, clear, concrete, and easy to read. Avoid jargon, API talk, code, benchmark details, and marketing language.",
        },
        {
          role: "user",
          content: [
            "Generate one fresh post for the AI Daily Notes feed.",
            "The topic should be an interesting AI news item for regular readers: new products, robots, smart devices, apps, creative tools, healthcare uses, education, transport, home gadgets, entertainment, science stories, or everyday life changes.",
            "Do not write a technical article. Avoid APIs, SDKs, documentation, deployment, coding, developer tooling, benchmarks, model internals, infrastructure, or implementation details.",
            "The content field must be at least 800 characters long.",
            "Explain why the news is interesting, what changed, who may use it, and what practical or social consequences it may have.",
            "Choose a substantially different angle from the recent posts below. Do not reuse their titles, main thesis, or source URLs.",
            JSON.stringify({ recentPosts }),
            "Use only the fetched research sources below as factual context for the post. Pick 1-4 relevant sources from them and return those exact title, publisher, and url values in the sources field.",
            "Do not cite or return any source that is not present in fetchedResearchSources.",
            JSON.stringify({ fetchedResearchSources: researchSources }),
            "Write exclusively in Polish. Keep any necessary English product names unchanged, but do not use random foreign words or technical jargon.",
            "Do not mention that the post was generated by AI.",
            "Return only a valid JSON object matching this JSON Schema:",
            JSON.stringify(generatedPostJsonSchema),
          ].join("\n\n"),
        },
      ],
      temperature: 0.85,
      response_format: {
        type: "json_object",
      },
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`GenAI request failed with ${response.status}: ${details}`);
  }

  const data = (await response.json()) as {
    choices?: Array<{
      message?: {
        content?: string;
      };
    }>;
  };
  const outputText = data.choices?.[0]?.message?.content;

  if (!outputText) {
    throw new Error("GenAI response did not include message content.");
  }

  return validateGeneratedPostSources(
    parseGeneratedPostDraft(outputText),
    researchSources,
  );
}

function parseGeneratedPostDraft(value: string): GeneratedPostDraft {
  try {
    return generatedPostDraftSchema.parse(JSON.parse(value));
  } catch (error) {
    const details =
      error instanceof Error ? error.message : "Unknown parse error.";

    throw new Error(`Failed to parse generated post draft: ${details}`);
  }
}

function validateGeneratedPostSources(
  draft: GeneratedPostDraft,
  researchSources: ResearchSource[],
): GeneratedPostDraft {
  const allowedSources = new Map(
    researchSources.map((source) => [normalizeUrl(source.url), source]),
  );
  const selectedSources = draft.sources
    .map((source) => allowedSources.get(normalizeUrl(source.url)))
    .filter((source): source is ResearchSource => Boolean(source))
    .slice(0, 4);

  if (selectedSources.length < 1) {
    throw new Error("GenAI response did not include enough valid sources.");
  }

  return {
    ...draft,
    sources: selectedSources.map((source) => ({
      title: source.title,
      publisher: source.publisher,
      url: source.url,
    })),
  };
}

function normalizeUrl(url: string) {
  try {
    const parsedUrl = new URL(url);
    parsedUrl.hash = "";

    return parsedUrl.toString();
  } catch {
    return url;
  }
}
